name: flutter_local_timezone
description: A Flutter plugin to get the current device's timezone in standard format.
version: 0.0.1
author: Pavels Gurskis <pavels.gurskis@gmail.com>

environment:
  sdk: ">=2.17.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: ai.achieveaup.flutter_local_timezone
        pluginClass: FlutterLocalTimezonePlugin
      ios:
        pluginClass: FlutterLocalTimezonePlugin
      macos:
        pluginClass: FlutterLocalTimezonePlugin
      linux:
        pluginClass: FlutterLocalTimezonePlugin
      windows:
        pluginClass: FlutterLocalTimezonePlugin

dependencies:
  flutter:
    sdk: flutter
