name: flutter_local_timezone
description: A Flutter plugin to get the current device's timezone in standard format.
version: 0.0.1
author: Pavels Gurskis <pavels.gurskis@gmail.com>

environment:
  sdk: ">=2.17.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_local_timezone
        pluginClass: FlutterLocalTimezonePlugin
      ios:
        pluginClass: FlutterLocalTimezonePlugin
      macos:
        pluginClass: FlutterLocalTimezonePlugin
      linux:
        pluginClass: FlutterLocalTimezonePlugin
      windows:
        pluginClass: FlutterLocalTimezonePlugin
      web:
        pluginClass: FlutterLocalTimezoneWeb
        fileName: flutter_local_timezone_web.dart


dependencies:
  flutter:
    sdk: flutter
